# Generated by Django 4.1.5 on 2023-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIocco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('clase', models.CharField(max_length=15)),
                ('municion', models.CharField(max_length=15)),
            ],
        ),
    ]
